### ISSUE TITLE
感谢楼主开源，能否开源ijkplayer那边你修改的源码？

### ISSUE THREAD

**Issue by KupoGu** [ILoveLin/ijkplayer_Record_Player#1]

**Comment by ILoveLin** [comment]
过几天添加个UI进去 ,能满足大部分需求

**Comment by KupoGu** [comment]
> 过几天添加个UI进去 ,能满足大部分需求
主要是你的底层修改录屏一直是失败的，貌似跟ui没啥关系

**Comment by ILoveLin** [comment]
确实和UI没关系，只支持RTSP  RTMP  HTTP   直播流，截图和录像，点播的视频不行的都不能使用~~~
过几天我更新下代码，rtsp需要配置下option参数这边我还没update，一直在忙
如果一直失败看你的错误日志，
请查看，权限是否申请了？

**Comment by miller8** [comment]
感谢楼主开源，能否开源ijkplayer那边你修改的源码?
