### ISSUE TITLE
背景播放和静音功能怎么没有效果呢

### ISSUE THREAD

**Issue by leigel** [ILoveLin/ijkplayer_Record_Player#2]

**Comment by ILoveLin** [comment]
我没理解你想表达的意思？是不是只播放音频?

**Comment by leigel** [comment]
> 我没理解你想表达的意思？是不是只播放音频?

就是切换到后台的时候，后台继续播放声音，并且录香不停止。重新切换到前台的时候，界面还是正常播放，录像继续正常进行
