### ISSUE TITLE
rtsp视频录制时碰到问题

### ISSUE THREAD

**Issue by jianghaikuan** [ILoveLin/ijkplayer_Record_Player#4]
1、视频录制成功，保存成功后，在查看播放时，进度条会直播跳到10秒位置开始播放。前几秒没有了。

2、正在播放的视频，旋转屏幕，播放画面被拉伸。

**Comment by ILoveLin** [comment]
要不你试一试VLC？ 




| |
tongzhengtong
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年3月10日 ***@***.***> 写道：

1、视频录制成功，保存成功后，在查看播放时，进度条会直播跳到10秒位置开始播放。前几秒没有了。

2、正在播放的视频，旋转屏幕，播放画面被拉伸。

**Comment by ILoveLin** [comment]
什么bug
