### ISSUE TITLE
大佬求救

### ISSUE THREAD

**Issue by yunxiangwu** [ILoveLin/ijkplayer_Record_Player#6]
Android 8.1上录制视频不定时崩溃，能帮忙分析吗，报的是c的错，微信：wuyunxiang201205
![image](https://user-images.githubusercontent.com/16435800/116501373-311da100-a8e3-11eb-8326-382f8b4f179f.png)

**Comment by ILoveLin** [comment]
你去我github上面下载，GodPlayer项目找到         VlcPlayerActivity，用里面的VLC吧，健壮性更强，也可以截图录像等等（支持rtsp，rtmp，http等等的直播或者转播视频的录像，截图），健壮性比ijk好很多，自己看下代码，把你用到的直接复制到新的项目里面就行，用不了十分钟，很快你就能集成好你要的代码。
