### ISSUE TITLE
感谢作者开放，发现截图会出现bug

### ISSUE THREAD

**Issue by mconnm** [ILoveLin/ijkplayer_Record_Player#8]
08-23 07:51:56.404 24902-25090/? I/System.out: Screenshot---srcBitmap：11519/0
08-23 07:51:56.874 3996-4038/? E/[cmshow][MemePlayer]MemeBornPlayerManager: currentActionState
     canRecycle:false
08-23 07:51:57.024 836-836/? I/MSM-irqbalance: Decided to move IRQ215 from CPU0 to CPU3
08-23 07:51:57.034 24902-25108/? I/System.out: Screenshot---srcBitmap--start
08-23 07:51:57.034 24902-25108/? D/IJKMEDIA: =============>start snapshot
08-23 07:51:57.034 24902-25108/? D/IJKMEDIA: =============>640 X 352 === 0
08-23 07:51:57.034 24902-25108/? A/libc: Fatal signal 11 (SIGSEGV) in tid 25108 (Thread-2608)
08-23 07:51:57.094 445-445/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-23 07:51:57.094 445-445/? I/DEBUG: Build fingerprint: 'vivo/PD1522A/PD1522A:5.1.1/LMY47V/compiler09121524:user/release-keys'
08-23 07:51:57.094 445-445/? I/DEBUG: Revision: '0'
08-23 07:51:57.094 445-445/? I/DEBUG: ABI: 'arm'
08-23 07:51:57.094 445-445/? I/DEBUG: pid: 24902, tid: 25108, name: Thread-2608  >>> tech.bova.android <<<
08-23 07:51:57.094 445-445/? I/DEBUG: signal 11 (SIGSEGV), code 0 (SI_USER), fault addr 0x0
08-23 07:51:57.104 433-433/? I/SurfaceFlinger: FPS: 60
08-23 07:51:57.114 445-445/? I/DEBUG:     r0 a2fd400c  r1 00000000  r2 000009fc  r3 00000004
08-23 07:51:57.114 445-445/? I/DEBUG:     r4 00000000  r5 a2fd400c  r6 00000001  r7 00000a00
08-23 07:51:57.114 445-445/? I/DEBUG:     r8 00000160  r9 00000000  sl 00000000  fp 12c8f190
08-23 07:51:57.114 445-445/? I/DEBUG:     ip 80000000  sp a60c4ad8  lr a79afe39  pc f72f5a2c  cpsr 800f0010
08-23 07:51:57.114 445-445/? I/DEBUG: backtrace:
08-23 07:51:57.114 445-445/? I/DEBUG:     #00 pc 0000fa2c  /system/lib/libc.so (__memcpy_base+60)
08-23 07:51:57.114 445-445/? I/DEBUG:     #01 pc 00019e35  /data/app/tech.bova.android-1/lib/arm/libijkplayer.so (ffp_get_current_frame_l+108)
08-23 07:51:57.114 445-445/? I/DEBUG:     #02 pc 0001d4a7  /data/app/tech.bova.android-1/lib/arm/libijkplayer.so (ijkmp_get_current_frame+18)
08-23 07:51:57.114 445-445/? I/DEBUG:     #03 pc 0001f4f7  /data/app/tech.bova.android-1/lib/arm/libijkplayer.so
08-23 07:51:57.114 445-445/? I/DEBUG:     #04 pc 00775f23  /data/dalvik-cache/arm/data@app@tech.bova.android-1@base.apk@classes.dex
08-23 07:51:57.374 26445-26672/? D/Wadl_WadlRemoteService: sendRemoteCommand cmd=WADL.REVERSE_HEART_CMD,count=1
08-23 07:51:57.374 3996-4015/? I/Wadl_WadlProxyServiceManager: transferAsync from Service cmd=WADL.REVERSE_HEART_CMD
08-23 07:51:57.374 3996-15728/? I/WadlProxyServiceMonitor: onRecvHeart lastRecvReportTime=133493518,lastCheckTime=133413440,lastReportCount=4
08-23 07:51:57.674 450-1520/? V/AudioFlinger: sleep uid:10136, mState:6, name:4097
08-23 07:51:57.674 1420-2619/? V/VivoStats: note what = 12, arg1 = 0, arg2 = 10136
08-23 07:51:57.674 2428-2449/? V/PowerEffectManager: noteAudioLocked stop uid = 10136
08-23 07:51:57.684 450-1520/? D/AudioFlinger: stopOutput_POM , POM_id:24902
08-23 07:51:57.684 450-1517/? D/AudioPolicyManager: stopOutput_POM, output:2, stream:3, session:755, pom_id:24902
08-23 07:51:57.684 450-1517/? I/AudioPolicyManager: stopOutput_POM: 24902 0 0
08-23 07:51:57.684 450-1517/? D/AudioPolicyManager: stopOutput isCallPOMStateChange :0, refCount:1
08-23 07:51:57.684 450-1517/? D/AudioPolicyManager: stopOutput isCallPOMStateChange :0, refCount:0
08-23 07:51:57.684 450-1517/? D/AudioPolicyManager: setOutputDevice() mMutePrevDevice 0002
08-23 07:51:57.684 450-1517/? I/AudioPolicyManager: ###### POM Stack0:  0 0 1
08-23 07:51:57.684 450-1517/? I/AudioPolicyManager: ###### POM Stack1:  24902 0 0
08-23 07:51:57.684 450-1517/? I/AudioPolicyManager: remove pom records for 24902.
08-23 07:51:57.904 445-445/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
08-23 07:51:57.904 24902-25071/? W/AudioTrack: releaseBuffer() track 0xa418eca0 disabled due to previous underrun, restarting
08-23 07:51:57.914 450-1527/? D/AudioFlinger: startOutput_POM , POM_id:24902
08-23 07:51:57.914 450-1527/? D/AudioPolicyManager: startOutput_POM output:2, stream:3, session:755, pom_id:24902
08-23 07:51:57.914 450-1527/? I/AudioPolicyManager: startOutput_POM: 24902 0 1
08-23 07:51:57.914 450-1527/? D/AudioPolicyManager: startOutput isCallPOMStateChange :0, refCount:1
08-23 07:51:57.914 450-1527/? D/AudioPolicyManager: setOutputDevice() mMutePrevDevice 0000
08-23 07:51:57.914 1420-25109/? I/ActivityManager: handleApplicationCrash calltech.bova.android
08-23 07:51:57.914 1420-1498/? I/BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
08-23 07:51:57.914 1420-25109/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1738 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:14037 com.android.server.am.NativeCrashListener$NativeCrashReporter.run:86 <bottom of call stack> <bottom of call stack> 
08-23 07:51:57.914 2406-2424/? D/SLService: ppCra : tech.bova.android pid : 24902
08-23 07:51:57.914 1420-25109/? W/ActivityManager:   Force finishing activity 1 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.cusijkplayer
08-23 07:51:57.914 450-1520/? D/audio_hw_primary: out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
08-23 07:51:57.914 450-1520/? V/msm8916_platform: platform_get_output_snd_device: enter: output devices(0x2)
08-23 07:51:57.914 450-1520/? V/msm8916_platform: platform_get_output_snd_device: exit: snd_device(speaker)
08-23 07:51:57.914 450-1520/? D/audio_hw_primary: select_devices, usecase_flag:0, out_snd_device:2
08-23 07:51:57.914 450-1520/? D/audio_hw_primary: audio_set_default_i2s_rate: samplerate=KHZ_48
08-23 07:51:57.914 2627-2627/? I/LogUploadService: start onCreate
08-23 07:51:57.914 450-1520/? D/audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
08-23 07:51:57.914 450-1520/? V/audio_hw_fm: audio_extn_fm_set_parameters: enter
08-23 07:51:57.914 2627-2627/? I/LogUploadService: start onStart
08-23 07:51:57.914 450-1520/? V/audio_hw_fm: audio_extn_fm_set_parameters: exit
08-23 07:51:57.914 450-1520/? V/audio_hw_extn: audio_extn_hpx_set_parameters
08-23 07:51:57.914 450-1520/? V/audio_hw_extn: audio_extn_asphere_set_parameters: property not set!!! not doing anything
08-23 07:51:57.914 450-1520/? V/AudioFlinger: processConfigEvents_l() DONE thread 0xf0f29008
08-23 07:51:57.914 2627-2627/? D/LogUploadService: process name = tech.bova.android
08-23 07:51:57.914 2627-2627/? D/LogUploadService: Logsystem_crashed = 0
08-23 07:51:57.914 2627-2627/? D/LogUploadService:  isCancel = false
08-23 07:51:57.914 1420-25109/? V/VivoStats: noteActivityPausedLocked uid = 10136
08-23 07:51:57.914 450-1527/? I/AudioPolicyManager: ###### POM Stack0:  0 0 1
08-23 07:51:57.914 1420-25109/? W/ActivityManager: tech.bova.android crash because Native crash
08-23 07:51:57.914 450-1527/? I/AudioPolicyManager: ###### POM Stack1:  24902 0 1
08-23 07:51:57.914 1420-25109/? W/ActivityManager: tech.bova.android crash because Native crash, so we dexopt for this pakcage
08-23 07:51:57.914 2627-7252/? I/LogUploadService: fileName = stability
08-23 07:51:57.914 1420-2031/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1373 com.vivo.services.perfservice.VivoPerfService.sendMCIntent:576 com.vivo.services.perfservice.VivoPerfService$PerfHandler.handleMessage:189 android.os.Handler.dispatchMessage:102 android.os.Looper.loop:135 
08-23 07:51:57.914 1420-1496/? W/ActivityManager: user_experience_improve_plan is open.Skipping crash dialog.
08-23 07:51:57.924 2627-7252/? I/LogUploadService: fileName = stability, size = 59805
08-23 07:51:57.924 2627-7252/? I/LogUploadService: fileName = performance
08-23 07:51:57.924 1420-2031/? I/VivoPerfService: excepType:4 procName:tech.bova.android background:true
08-23 07:51:57.924 2627-7252/? I/LogUploadService: fileName = performance, size = 580
08-23 07:51:57.924 450-1520/? D/AudioFlinger: isReady, mReadyCheckCount 0
08-23 07:51:57.934 450-1520/? D/AudioFlinger: isReady, mReadyCheckCount 1
08-23 07:51:57.934 1420-1964/? W/InputDispatcher: channel '68aaf58 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.cusijkplayer (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-23 07:51:57.934 1420-1964/? E/InputDispatcher: channel '68aaf58 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.cusijkplayer (server)' ~ Channel is unrecoverably broken and will be disposed!
08-23 07:51:57.934 1420-1964/? W/InputDispatcher: channel '98bed41 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.IndexActivity_IPCamera (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-23 07:51:57.934 1420-1964/? E/InputDispatcher: channel '98bed41 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.IndexActivity_IPCamera (server)' ~ Channel is unrecoverably broken and will be disposed!
08-23 07:51:57.944 1420-1494/? D/SensorService: 0x7f7b1b4080 addFd fd=418
08-23 07:51:57.944 1420-1493/? D/SensorService: 0x7f7b1b4080 Looper error 418
08-23 07:51:57.944 1420-1493/? D/SensorService: 0x7f7b1b4080 removeFd fd=418
08-23 07:51:57.944 1420-1494/? D/SensorService: 0x7f7b2fa650 addFd fd=403
08-23 07:51:57.944 1420-1493/? D/SensorService: 0x7f7b2fa650 Looper error 403
08-23 07:51:57.944 1420-1493/? D/SensorService: 0x7f7b2fa650 removeFd fd=403
08-23 07:51:57.944 450-1520/? D/AudioFlinger: isReady, mReadyCheckCount 2
08-23 07:51:57.944 2627-7252/? I/LogUploadService: Log File has created
08-23 07:51:57.944 2627-7252/? I/LogUploadService: Panic folder is exists = false
08-23 07:51:57.944 2627-7252/? I/LogUploadService: Dropbox folder is exists = true
08-23 07:51:57.944 2627-7252/? I/LogUploadService: My dropbox folder is exists = true
08-23 07:51:57.954 450-1520/? D/AudioFlinger: isReady, mReadyCheckCount 3
08-23 07:51:57.954 2627-7252/? I/LogUploadService: ANR folder is exists = false
08-23 07:51:57.954 2627-7252/? D/CurrentVersionUtil: imei = 869765024945006
08-23 07:51:57.954 1420-2646/? I/WindowState: WIN DEATH: Window{15e8f196 u0 SurfaceView}
08-23 07:51:57.954 450-1526/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
08-23 07:51:57.964 1420-1437/? W/MediaFocusControl:   AudioFocus   audio focus client died
08-23 07:51:57.964 1420-1437/? I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@2b7457b3
08-23 07:51:57.964 1420-2440/? D/SensorService: ~SensorEventConnection(0x7f7b2fa650)
08-23 07:51:57.964 1420-2440/? D/SensorService: 6 active sensors
08-23 07:51:57.964 1420-2440/? D/SensorService: 0: disabling handle=0x00000001
08-23 07:51:57.964 1420-2440/? D/SensorService: SensorDevice::activate: ident=0x7f7b2fa650, handle=0x00000001, enabled=0, count=2
08-23 07:51:57.964 1420-2440/? D/SensorService: disable index=1
08-23 07:51:57.964 1420-2440/? D/SensorService: 	>>> actuating h/w batch 1 0 66667000 0
08-23 07:51:57.964 1420-2440/? W/VivoSensorTest: int SensorsContext::batch(int, int, int64_t, int64_t) handle 0 flags 0 period_ns 66667000 timeout 0
08-23 07:51:57.964 1420-2440/? W/qti_sensors_hal: batch:sensor(android.sensor.accelerometer) handle:0 flags:0x0 period_ns 66667000 timeout 0
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[0].handle=0x00000001
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[1].handle=0x00000006
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[2].handle=0x0000000d
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[3].handle=0x00000012
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[4].handle=0x00000013
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b2fa650 for sensor[5].handle=0x00000017
08-23 07:51:57.964 1420-2440/? D/SensorService: ~SensorEventConnection(0x7f7b1b4080)
08-23 07:51:57.964 1420-2440/? D/SensorService: 6 active sensors
08-23 07:51:57.964 1420-2440/? D/SensorService: 0: disabling handle=0x00000001
08-23 07:51:57.964 1420-2440/? D/SensorService: SensorDevice::activate: ident=0x7f7b1b4080, handle=0x00000001, enabled=0, count=1
08-23 07:51:57.964 1420-2440/? D/SensorService: disable index=0
08-23 07:51:57.964 1420-2440/? D/SensorService: 	>>> actuating h/w activate handle=1 enabled=0
08-23 07:51:57.964 1420-2440/? W/VivoSensorTest: activate: handle is 0, en is 0
08-23 07:51:57.964 2627-2627/? D/LogUploadService:  FileTool.size(file) = 60387
08-23 07:51:57.964 2627-2627/? I/LogUploadService: System.currentTimeMillis() = 1629676317973, lastAskTime = 1629644211937, mLimitTime = 86400000
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[0].handle=0x00000001
08-23 07:51:57.964 1420-2440/? D/SensorService: ... and it was the last connection
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[0].handle=0x00000006
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[1].handle=0x0000000d
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[2].handle=0x00000012
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[3].handle=0x00000013
08-23 07:51:57.964 1420-2440/? D/SensorService: removing connection 0x7f7b1b4080 for sensor[4].handle=0x00000017
08-23 07:51:57.964 1420-2595/? W/InputDispatcher: Attempted to unregister already unregistered input channel '68aaf58 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.cusijkplayer (server)'
08-23 07:51:57.964 1420-2595/? I/WindowState: WIN DEATH: Window{68aaf58 u0 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.cusijkplayer}
08-23 07:51:57.974 1420-1437/? W/InputDispatcher: Attempted to unregister already unregistered input channel '98bed41 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.IndexActivity_IPCamera (server)'
08-23 07:51:57.974 1420-1437/? I/WindowState: WIN DEATH: Window{98bed41 u0 tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.IndexActivity_IPCamera}
08-23 07:51:58.014 474-474/? I/Zygote: Process 24902 exited due to signal (11)
08-23 07:51:58.014 1420-2014/? I/ActivityManager: Process tech.bova.android (pid 24902) has died
08-23 07:51:58.014 1420-2014/? D/ActivityManager: cleanUpApplicationRecord -- 24902
08-23 07:51:58.024 22954-22954/? D/baidu_location_service: baidu location service stop ...
08-23 07:51:58.024 1420-2185/? D/LocationManagerService: removeUpdates  packageName tech.bova.android pid:22954 uid:10136
08-23 07:51:58.024 1420-2609/? D/LocationManagerService: removeUpdates  packageName tech.bova.android pid:22954 uid:10136
08-23 07:51:58.024 1420-1503/? D/PhoneWindow: DEBUG_SYSTEMUI:origin statusbar style 
08-23 07:51:58.024 1420-1503/? D/PhoneWindow: DEBUG_SYSTEMUI:IconColor=1
08-23 07:51:58.024 1420-1503/? D/PhoneWindow: DEBUG_SYSTEMUI:StatusBarColor final set ff000000
08-23 07:51:58.024 1420-1503/? I/ViewRootImpl: CPU Rendering VSync enable = true
08-23 07:51:58.024 1420-1503/? V/WindowManager: Adding window Window{89bbce9 u0 Starting tech.bova.android} at 13 of 23 (before Window{15e8f196 u0 SurfaceView EXITING})
08-23 07:51:58.044 25111-25111/? I/PMFunc: prepare 0 tech.bova.android
08-23 07:51:58.054 1420-2014/? I/ActivityManager: Start proc 25111:tech.bova.android/u0a136 for activity tech.bova.android/com.createiot.uddgps1.Activity.IPCamera.IndexActivity_IPCamera
08-23 07:51:58.054 2627-2627/? I/LogUploadService: start onDestroy
08-23 07:51:58.054 2428-2449/? D/NailDaemonService: process died pid : 24902 mVivoNailPid: 3396
08-23 07:51:58.054 2406-6777/? I/FloatWindowManagerService: get died  is : 24902 ; id is : 10136
08-23 07:51:58.064 1420-2043/? D/ScreenBrightnessModeRestore: pakage name is tech.bova.androidwith :10136
08-23 07:51:58.064 1420-2043/? D/ScreenBrightnessModeRestore:  onProcessDiedInner, pid = 24902 , mCurrentForceGroundPid = 24902 mAppName: tech.bova.android mWaitToRestore=false
08-23 07:51:58.064 1420-2043/? D/ScreenBrightnessModeRestore: mRunnable try to restore, mLastScreenBrightness: 200 mWaitToRestoreBrightness: false mWaitToRestoreMode: false mLastScreenMode: 0
08-23 07:51:58.064 450-1526/? I/OMX-VDEC-1080P: omx_vdec::component_deinit() complete
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: deleteDiedAppList_getUid()=10136
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: deleteDiedAppList_getPid()=24902
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: deleteDiedAppList_mForgroundInfo_pid=24902,mForgroundInfo_pkgName=tech.bova.android,mForgroundInfo_uid=10136,mBackgroundInfo_pid=2760,mBackgroundInfo_pkgName=com.bbk.launcher2,mBackgroundInfo_uid=10027
08-23 07:51:58.064 450-1520/? D/AudioFlinger: removeTrack_l, track:0xab52dda0, client:0xab5488e8, pid:24902
08-23 07:51:58.064 450-1520/? D/AudioFlinger: removeTrack_l TrackCount:0
08-23 07:51:58.064 450-1520/? V/AudioResampler: resampler load 36 -> 24 MHz due to delta -12 MHz from quality 7
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: getversionCode=10
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: getVersionName_name=2.2
08-23 07:51:58.064 450-1526/? I/OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=54
08-23 07:51:58.064 450-1526/? I/OMX-VDEC-1080P: Video slvp perflock released
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: getversionCode=10
08-23 07:51:58.064 2283-2865/? I/_V_UsageAppManager: getVersionName_name=2.2
08-23 07:51:58.074 2283-11134/? V/SingleDBHelper: ~~~~onOpen
08-23 07:51:58.074 2406-3180/? I/FloatWindowManagerService: get top = tech.bova.android
08-23 07:51:58.074 2406-3180/? I/FloatWindowManagerService: die is : tech.bova.android ; fore is : tech.bova.android
08-23 07:51:58.074 450-1520/? D/AudioFlinger: stopOutput_POM , POM_id:24902
08-23 07:51:58.074 450-1520/? D/AudioFlinger: ~TrackBase  mClient:0xab5488e8
08-23 07:51:58.074 450-1517/? D/AudioPolicyManager: stopOutput_POM, output:2, stream:3, session:755, pom_id:24902
08-23 07:51:58.074 450-1517/? I/AudioPolicyManager: stopOutput_POM: 24902 0 0
08-23 07:51:58.074 450-1517/? D/AudioPolicyManager: stopOutput isCallPOMStateChange :0, refCount:1
08-23 07:51:58.074 450-1517/? D/AudioPolicyManager: stopOutput isCallPOMStateChange :0, refCount:0
08-23 07:51:58.074 450-1517/? D/AudioPolicyManager: setOutputDevice() mMutePrevDevice 0002
08-23 07:51:58.074 450-1517/? I/AudioPolicyManager: ###### POM Stack0:  0 0 1
08-23 07:51:58.074 450-1517/? I/AudioPolicyManager: ###### POM Stack1:  24902 0 0
08-23 07:51:58.074 450-1517/? I/AudioPolicyManager: remove pom records for 24902.

**Comment by ILoveLin** [comment]
请移步到我的GodPlayer,使用vlc的 你要的功能都有~
